spring:
  datasource:
    master:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/research
      username: root
      password: password

    slave:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:23306/research
      username: root
      password: password


doma:
  dialect: MYSQL
  sql-file-repository: no_cache
